<?php

namespace AnyMedia\Interpresso\Tests\Feature;

use PHPUnit\Framework\Attributes\Test;

use Illuminate\Foundation\Testing\RefreshDatabase;
use OpenAI\Laravel\Facades\OpenAI;
use AnyMedia\Interpresso\Helpers\LanguageHelper;
use AnyMedia\Interpresso\Jobs\FindMissingTranslationsJob;
use AnyMedia\Interpresso\Jobs\ImportLanguagesJob;
use AnyMedia\Interpresso\Jobs\ImportTranslationsJob;
use AnyMedia\Interpresso\Models\Language;
use AnyMedia\Interpresso\Models\Translation;
use AnyMedia\Interpresso\Models\Translator;
use AnyMedia\Interpresso\Services\ImportLanguageService;
use AnyMedia\Interpresso\Services\ImportTranslationService;
use AnyMedia\Interpresso\Services\MissingTranslationService;
use AnyMedia\Interpresso\Tests\BaseTestCase;

class ImportTranslationServiceTest extends BaseTestCase
{
    use RefreshDatabase;

    /**
     * @var Translator
     */
    protected Translator $admin;

    public function setUp(): void
    {
        /**
         * Background import languages and translations from ./data folder
         */
        parent::setUp(); // TODO: Change the autogenerated stub
        OpenAI::fake();
        $languages = Language::all();
        $this->admin = $this->createAdmin($languages);
        $this->actingAs($this->admin);
        ImportLanguagesJob::dispatch((new ImportLanguageService()), $this->admin);
    }

    #[Test]
    public function import_translation_service_translations_successful(): void
    {
        /**
         * Given there are 4 languages imported and no translations
         */
        $this->assertEquals(0, Translation::count());

        /**
         * When importing the translations
         */
        ImportTranslationsJob::dispatch(new ImportTranslationService(), $this->admin);

        /**
         * Then it will create Database entry for each translation value excluding vendor translations
         */
        $total = resolve(LanguageHelper::class)->count_all_array_values_in_directory($this->getTempDataPath());
        $this->assertEquals($total, Translation::count());
    }

    #[Test]
    public function import_translation_service_missing_translations_successful(): void
    {
        /**
         * Given there are 4 languages imported and translations AND one new language without translations
         */
        ImportTranslationsJob::dispatch(new ImportTranslationService());

        $total = count(array_unique(Translation::selectRaw('count(*) as total')->groupBy('language_id')->orderBy('language_id')->pluck('total')->all()));

        $this->assertNotEquals(1, $total);

        /**
         * When finding new missing translations
         */
        FindMissingTranslationsJob::dispatch(new MissingTranslationService());

        /**
         * Then it will create the missing translations entries for each language
         */
        $total = count(array_unique(Translation::selectRaw('count(*) as total')->groupBy('language_id')->orderBy('language_id')->pluck('total')->all()));

        $this->assertEquals(1, $total);


    }

}
