<?php

namespace AnyMedia\Interpresso\Tests\Feature;

use PHPUnit\Framework\Attributes\Test;

use Illuminate\Foundation\Testing\RefreshDatabase;
use AnyMedia\Interpresso\Jobs\Batch\BatchProcessor;
use AnyMedia\Interpresso\Jobs\ImportLanguagesJob;
use AnyMedia\Interpresso\Jobs\ImportTranslationsJob;
use AnyMedia\Interpresso\Models\Language;
use AnyMedia\Interpresso\Models\Translation;
use AnyMedia\Interpresso\Models\Translator;
use AnyMedia\Interpresso\Services\ImportLanguageService;
use AnyMedia\Interpresso\Services\ImportTranslationService;
use AnyMedia\Interpresso\Services\MissingTranslationService;
use AnyMedia\Interpresso\Tests\BaseTestCase;

class ImportLanguageServiceTest extends BaseTestCase
{
    use RefreshDatabase;

    /**
     * @var ImportLanguageService
     */
    protected ImportLanguageService $importLanguageService;

    /**
     * @var Translator
     */
    protected Translator $admin;

    public function setUp(): void
    {
        /**
         * Background import languages and translations from ./data folder
         */
        parent::setUp(); // TODO: Change the autogenerated stub
        Language::query()->delete();
        $this->importLanguageService = new ImportLanguageService();
        $languages = Language::all();
        $this->admin = $this->createAdmin($languages);
        $this->actingAs($this->admin);
    }

    #[Test]
    public function import_translation_service_languages_successful(): void
    {
        /**
         * Given there are no languages in the database and 4 languages in the lang folder
         */
        Language::query()->delete();
        $this->assertEquals(0, Language::count());

        /**
         * When importing new languages
         */
        ImportLanguagesJob::dispatch($this->importLanguageService, $this->admin);

        /**
         * Then it will create 4 language records
         */
        $this->assertEquals(4, Language::count());
    }
}
