<?php

namespace AnyMedia\Interpresso\Tests\Feature;

use PHPUnit\Framework\Attributes\Test;

use Illuminate\Foundation\Testing\RefreshDatabase;
use AnyMedia\Interpresso\Jobs\ImportLanguagesJob;
use AnyMedia\Interpresso\Jobs\ImportTranslationsJob;
use AnyMedia\Interpresso\Models\Language;
use AnyMedia\Interpresso\Models\Setting;
use AnyMedia\Interpresso\Models\Translator;
use AnyMedia\Interpresso\Services\ImportLanguageService;
use AnyMedia\Interpresso\Services\ImportTranslationService;
use AnyMedia\Interpresso\Tests\BaseTestCase;

class TranslationsTest extends BaseTestCase
{
    use RefreshDatabase;

    /**
     * @var ImportTranslationService
     */
    protected ImportTranslationService $importTranslationService;

    /**
     * @var Language
     */
    protected Language $language;

    protected Translator $admin;

    /**
     * @return void
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $languages = Language::all();
        $this->admin = $this->createAdmin($languages);
        ImportLanguagesJob::dispatch((new ImportLanguageService()), $this->admin);
        ImportTranslationsJob::dispatch(new ImportTranslationService(), $this->admin);
    }

    #[Test]
    public function transl_admin_can_access_trans_service_and_see_admin_options(): void
    {
        // File export controls belong to the supported file-loader mode.
        Setting::query()->firstOrFail()->update(['db_loader' => false]);
        Setting::getFreshCached();

        /**
         * Given there are 4 languages with translations
         */
        $this->language = Language::find(1);
        $languageTwo = Language::find(4);

        /**
         * When an admin user accesses the Translatiosn UI of en
         */
        $this->actingAs($this->admin)
            ->get(route('interpresso.translations', $this->language))
            /**
             * Then he should see all options
             */
            ->assertSee(__('interpresso::translations.title', ['language' => $this->language->name, 'code' => $this->language->code]))
            ->assertSee(__('interpresso::translations.button.export_translation'))
            ->assertSee(__('interpresso::translations.button.approve_all', ['language_code' => $this->language->code]))
            ->assertDontSee(__('interpresso::translations.button.export_all_translations'))
            ->assertSee(__('interpresso::translations.checkbox_filter_button'))
            ->assertSee(__('interpresso::translations.table.action.translate'))
            ->assertDontSee(__('interpresso::translations.title', ['language' => $languageTwo->name, 'code' => $languageTwo->code]));
    }

    #[Test]
    public function transl_translator_can_access_assigned_language_but_dont_see_admin_options(): void
    {
        /**
         * Given there are 4 languages with translations and user is not admin but translator
         */
        $this->language = Language::find(1);
        $languageTwo = Language::find(4);
        $translator = factory(Translator::class)->create();
        $translator->languages()->attach(Language::find(1)->id);
        /**
         * When the translator accesses an assigned langauge
         */
        $this->actingAs($translator)
            ->get(route('interpresso.translations', $this->language))
            /**
             * Then he should see only translator available options
             */
            ->assertSee(__('interpresso::translations.title', ['language' => $this->language->name, 'code' => $this->language->code]))
            ->assertDontSee(__('interpresso::translations.button.export_translation'))
            ->assertDontSee(__('interpresso::translations.button.approve_all', ['language_code' => $this->language->code]))
            ->assertDontSee(__('interpresso::translations.button.export_all_translations'))
            ->assertSee(__('interpresso::translations.checkbox_filter_button'))
            ->assertSee(__('interpresso::translations.table.action.translate'))
            ->assertDontSee(__('interpresso::translations.title', ['language' => $languageTwo->name, 'code' => $languageTwo->code]));
    }

    #[Test]
    public function transl_translator_cannot_access_not_assigned_language(): void
    {
        /**
         * Given there are 4 languages with translations and user is not admin but translator
         */
        $this->language = Language::find(1);
        $languageTwo = Language::find(4);
        $translator = factory(Translator::class)->create();
        $translator->languages()->attach(Language::find(4)->id);

        /**
         * When the translator accesses an not assigned langauge
         */
        $this->actingAs($translator)
            ->get(route('interpresso.translations', $this->language))
            /**
             * Then it should returns 403
             */
            ->assertStatus(403);
    }

    #[Test]
    public function transl_guest_cannot_access_page(): void
    {
        $this->language = Language::find(1);
        $this->get(route('interpresso.translations', $this->language))
            ->assertRedirect(route('interpresso.login'));
    }


}
